### ISSUE TITLE
Secret adddress for registration

### ISSUE THREAD

**Issue by cankisagun** [levackt/secret-cred#2]
secret1r6ta065klvexs6tj68u2wrtg034yw7leyt4qfn

**Comment by levackt** [comment]
[Register TX](https://explorer.secrettestnet.io/transactions/88751496AD113D602AC0E56A60DE2738E8BF805735782CF7E244316AF0BB76A9
)

Registered cred_id=VOggqrrAHnZoBjBXon3NXg for cankisagun

[One of the allocations](https://explorer.secrettestnet.io/transactions/22C3DC43EE0342DBBA68ED88A87F11049C3ADE394FF0003F80B0147431262E28)

You should be able to view your balance on holodeck now.
